apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: d2-live-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"

spec:
  tls:
  - hosts:
    - d2.atlas.lucas.tools
    secretName: d2-tls
  rules:
  - host: d2.atlas.lucas.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: d2-live
            port:
              name: web
