name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Coverage
      run: go test -v -covermode=count -coverprofile=covprofile ./...

    - name: Publish to coveralls.io
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: covprofile
